[aws]
symbol = 'îŒ½ '

[character]
format = '[ğŸŒµ || $symbol ](bold white)'

[battery]
full_symbol = 'ï•¸'
charging_symbol = 'ï–ƒ'
discharging_symbol = 'ï–‚'

[conda]
symbol = 'ï„Œ '

[dart]
symbol = 'î˜ '

[directory]
read_only = ' ï ½'

[docker]
symbol = 'ïŒˆ '

[elixir]
symbol = 'î‰µ '

[elm]
symbol = 'î˜¬ '

[git_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '

[haskell]
symbol = 'î˜Ÿ '

[hg_branch]
symbol = 'ï˜ '

[java]
symbol = 'î‰– '

[julia]
symbol = 'î˜¤ '

[memory_usage]
symbol = 'ï¡š '

[nim]
symbol = 'ïš¤ '

[nix_shell]
symbol = 'ï‹œ '

[nodejs]
symbol = 'î‰ '

[package]
symbol = 'ï£– '

[perl]
symbol = 'î© '

[php]
symbol = 'î˜ˆ '

[python]
symbol = 'î˜† '

[ruby]
symbol = 'îˆ¾ '

[rust]
symbol = 'î¨ '

[swift]
symbol = 'ï¯£ '
